location          = "North Europe"
acr_registry_name = "szymonctainerregistry01"
node_size         = "Standard_B2s"
aks_cluster_name  = "aks-szymon-cluster"
dns_prefix        = "szymon-cluster"
aks_service_cidr  = "10.0.4.0/24"
kube_dns_ip       = "10.0.4.10"